### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by sashaperigo** [sashaperigo/Drake-Hate#1]
Here's the starter code I was using when writing the first half of this code: 
- https://github.com/basti2342/retweet-bot/blob/master/retweet.py

**Comment by jameswenzel** [comment]
twitter sentiment datasets for nltk learning (do stanford's servers have room for nltk datasets? i'm not sure how much nltk takes up if just used for sentiment analysis, maybe just these.)
http://www.tweenator.com/index.php?page_id=13 <http://www.tweenator.com/index.php?page_id=13>
http://www.sananalytics.com/lab/twitter-sentiment/ <http://www.sananalytics.com/lab/twitter-sentiment/>



--
James Wenzel
UC Berkeley 2017 || Cognitive Science, concentration in Computational Modeling 
VP of Finance || Business Careers in Entertainment Club
(650) 305-1343

**Comment by jameswenzel** [comment]
sentiment140 dataset/links (huge): http://help.sentiment140.com/for-students/ <http://help.sentiment140.com/for-students/>
paper they wrote on their maximum entropy classifier (really doesn't seem to do much better than naive bayes, for what I assume is much more complexity & processing power [could be wrong]): http://cs.stanford.edu/people/alecmgo/papers/TwitterDistantSupervision09.pdf <http://cs.stanford.edu/people/alecmgo/papers/TwitterDistantSupervision09.pdf> interesting and useful points in methodology though (from what i've skimmed)

--
James Wenzel
UC Berkeley 2017 || Cognitive Science, concentration in Computational Modeling 
VP of Finance || Business Careers in Entertainment Club
(650) 305-1343

**Comment by sashaperigo** [comment]
Considering moving this thread out of Issues and into a Wiki page...

**Comment by sashaperigo** [comment]
Moved this info to the README!
